apiVersion: v1
kind: Service
metadata:
  labels:
    app: graphqlserv
  name: graphqlserv
spec:
  type: NodePort
  selector:
    app: graphqlserv
  ports:
  - port: 8014
    targetPort: 8014
    protocol: TCP
    nodePort: 30014