apiVersion: v1
kind: Service
metadata:
  labels:
    app: inventoryserv
  name: inventoryserv
spec:
  type: NodePort
  selector:
    app: inventoryserv
  ports:
  - port: 8011
    targetPort: 8011
    protocol: TCP
    nodePort: 30011