apiVersion: v1
kind: Service
metadata:
  labels:
    app: keydb
  name: keydb
spec:
  type: NodePort
  selector:
    app: keydb
  ports:
  - port: 6379
    targetPort: 6379
    protocol: TCP
    nodePort: 30002