apiVersion: v1
kind: Service
metadata:
  labels:
    app: notificationserv
  name: notificationserv
spec:
  type: NodePort
  selector:
    app: notificationserv
  ports:
  - port: 8012
    targetPort: 8012
    protocol: TCP
    nodePort: 30012