apiVersion: v1
kind: Service
metadata:
  labels:
    app: orderserv
  name: orderserv
spec:
  type: NodePort
  selector:
    app: orderserv
  ports:
  - port: 8013
    targetPort: 8013
    protocol: TCP
    nodePort: 30013