apiVersion: v1
kind: Service
metadata:
  labels:
    app: shopbd
  name: shopbd
spec:
  type: NodePort
  selector:
    app: shopbd
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
    name: topostgres
    nodePort: 30000