apiVersion: apps/v1
kind: Deployment
metadata:
  name: productserv
  labels:
    app: productserv
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: productserv
  template:
    metadata:
      labels:
        app: productserv
    spec:
      containers:
      - name: productserv
        image: rueies/productservice
        ports:
        - containerPort: 8010