apiVersion: v1
kind: Service
metadata:
  labels:
    app: productserv
  name: productserv
spec:
  type: NodePort
  selector:
    app: productserv
  ports:
  - port: 8010
    targetPort: 8010
    protocol: TCP
    nodePort: 30010