apiVersion: v1
kind: Service
metadata:
  labels:
    app: rmqbd
  name: rmqbd
spec:
  type: NodePort
  selector:
    app: rmqbd
  ports:
  - port: 5672
    targetPort: 5672
    protocol: TCP
    nodePort: 30001